name: CI for example.py changes

on:
  push:
    paths:
      - 'src/example_package_paguagag/example.py'
  pull_request:
    paths:
      - 'src/example_package_paguagag/example.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your preferred Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      # Build package
      - name: Build package
        run: |
          python -m build

      # Upload artifacts (e.g., dist files)
      - name: Upload distribution files
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*